#!/usr/bin/env python
"""Report class balance and size per split -- the context a bare AUROC hides.

Scaffold splitting deliberately puts unfamiliar chemotypes in the test set, and chemotype
correlates with activity, so the test split's positive rate drifts from the training split's. That
drift is expected. It is reported here because it bounds what a cross-paper AUROC comparison can
mean: two papers using different scaffold-split implementations are scoring different test
distributions, so a gap between them is not necessarily a modeling difference.

Usage: python scripts/split_diagnostics.py > results/SPLIT_DIAGNOSTICS.md
"""
import json
import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from src.datamodule import load_moleculenet

DATASETS = {
    "Tox21": "data/splits/tox21_scaffold.json",
    "BBBP": "data/splits/bbbp_scaffold.json",
    "BACE": "data/splits/bace_scaffold.json",
    "Lipo": "data/splits/lipophilicity_scaffold.json",
}


def main() -> int:
    print("# Split diagnostics\n")
    print("Bemis-Murcko scaffold splits, deterministic largest-group-first, 80/10/10.")
    print("Generated by `scripts/split_diagnostics.py` from the committed manifests.\n")
    print("| Dataset | Split | n | Label mean (pos. rate / target mean) |")
    print("|---|---|---|---|")

    notes = []
    for name, path in DATASETS.items():
        ds = load_moleculenet(name)
        Y = np.stack([d.y.view(-1).numpy() for d in ds]).astype(float)
        idx = json.loads(Path(path).read_text())["indices"]
        means = {}
        for part in ("train", "val", "test"):
            y = Y[idx[part]]
            with np.errstate(invalid="ignore"):
                mean = float(np.nanmean(y))
            means[part] = mean
            print(f"| {name} | {part} | {len(y)} | {mean:.4f} |")
        drift = means["test"] - means["train"]
        if abs(drift) > 0.1:
            notes.append(f"- **{name}**: test label mean drifts {drift:+.4f} from train "
                         f"({means['train']:.4f} -> {means['test']:.4f}).")

    print("\n## Notable label drift\n")
    if notes:
        print("\n".join(notes))
        print("\nThis is a property of scaffold splitting, not a bug: unfamiliar scaffolds carry")
        print("different activity rates. It matters for interpretation -- a metric measured on a")
        print("test split with a materially different class balance is not directly comparable to")
        print("a published number computed on a differently-built split of the same dataset.")
    else:
        print("No split shows a label-mean drift above 0.1.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
